# Generated by Django 2.2b1 on 2019-05-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='author',
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(db_index=True, default='ami', max_length=500),
        ),
    ]
